name: Select version and create release

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type: MAJOR | MINOR | PATCH'
        required: true
        default: 'MINOR'
        type: choice
        options:
          - PATCH
          - MINOR
          - MAJOR
      notify:
        description: 'Should workflow notify team?'
        required: true
        type: boolean


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.versionType }} environment"

      - name: Notify
        if: ${{ github.event.inputs.notify }}
        run: echo "Notifying of ${{ github.event.inputs.versionType }} deployment"
